import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-bright": "#f7f9fb",
        "secondary-fixed-dim": "#ffb59e",
        "on-primary-fixed": "#00174d",
        "surface-variant": "#e0e3e5",
        "primary-fixed": "#dbe1ff",
        surface: "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-container": "#ad3b00",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffdbd0",
        "outline-variant": "#c3c5d7",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#b5c4ff",
        background: "#f7f9fb",
        "primary-fixed-dim": "#b5c4ff",
        "secondary-container": "#fd591e",
        "on-primary-container": "#d4dcff",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed": "#3a0b00",
        "on-secondary-container": "#521300",
        "on-secondary": "#ffffff",
        tertiary: "#852b00",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        secondary: "#ae3200",
        "surface-container": "#eceef0",
        "surface-tint": "#1353d8",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#802a00",
        "on-tertiary-container": "#ffd4c5",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed-dim": "#ffb59a",
        "tertiary-fixed": "#ffdbcf",
        "on-tertiary-fixed": "#380d00",
        "error-container": "#ffdad6",
        "primary-container": "#1a56db",
        "on-surface": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "surface-container-low": "#f2f4f6",
        "on-surface-variant": "#434654",
        primary: "#003fb1",
        "on-primary-fixed-variant": "#003dab",
        "on-secondary-fixed-variant": "#852400",
        outline: "#737686",
        "surface-dim": "#d8dadc",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
